### ISSUE TITLE
Update reading list with 2 suggestions 

### ISSUE THREAD

**Issue by jmgoley** [readthelod/readthelod.github.io#8]
I tried my best, but I can't get the code to run to add (see below) to the "/_data)/reading-list.yml"

- title: Linked Data Notifications: A Resource-Centric Communication Protocol
  authors: Sarven Capadisli, Amy Guy, Christoph Lange, Sören Auer, Andrei Sambra & Tim Berners-Lee
  url: 
  keywords: Communications protocol, Decentralisation, Linked Data, Social Web
  
- title: Packaging research artefacts with RO-Crate
  authors: Soiland-Reyes, Stian, et al.
  url: 
  keywords: Data publishing, data packaging, FAIR, Linked Data, metadata, reproducibility, research object

**Comment by marc-portier** [comment]
yml values cannot have : sign in them --> so you have to surround the whole value side with "" so it accepts it as a string-value - fix underway
